apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: Node app that displays time - named ${{values.app_name}}
  annotations:
    github.com/project-slug: BackstageSSPPoC/${{values.app_name}}
    backstage.io/kubernetes-id: ${{ values.name }}

spec:
  type: service
  owner: development
  lifecycle: experimental