apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: github-actions-ci-cd-template
  title: GitHub Actions CI/CD Template
  description: Create a service with GitHub Actions CI/CD and direct Kubernetes deployment

spec:
  owner: group:default/development
  type: service

  parameters:
    - title: Service Configuration
      required:
        - component_id
        - environment
      properties:
        component_id:
          title: Component Name
          type: string
          description: Provide a component (microservice) name
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'

        environment:
          title: Environment
          type: string
          description: Deployment environment
          enum:
            - dev
            - prod

  steps:
    - id: fetch-base
      name: Fetch Base Template
      action: fetch:template
      input:
        url: ./template
        values:
          app_name: ${{ parameters.component_id }}
          app_env: ${{ parameters.environment }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: github.com?owner=BackstageSSPPoC&repo=${{ parameters.component_id }}
        description: Service ${{ parameters.component_id }}
        repoVisibility: public
        defaultBranch: main
        protectDefaultBranch: false

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoUrl: github.com?owner=BackstageSSPPoC&repo=${{ parameters.component_id }}
        catalogInfoPath: catalog-info.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in Catalog
        url: ${{ steps.register.output.entityRef }}